sudo: required
language: node_js
branches:
  only:
  - master
before_install:
  - npm i -g npm install -g angular-cli-ghpages @angular/cli
script:
- yarn build:gh-pages
- yarn ngh
cache:
  directories:
    - "node_modules"
