sudo: required
language: node_js
branches:
  only:
  - master
before_install:
  - npm i -g npm install -g angular-cli-ghpages @angular/cli
script:
- yarn ng build --prod --base-href "https://narhakobyan.github.io/socket-io-client/"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: 'dist'
  on:
    branch: master
cache:
  directories:
    - "node_modules"
